### ISSUE TITLE
Now available on NPM

### ISSUE THREAD

**Issue by shukriadams** [surrsurus/text-to-ipa#2]
Hey, this isn't an issue, just wanted to say thanks for this great lib, and that I wrapped it in an NPM package (https://www.npmjs.com/package/text-to-ipa)

**Comment by surrsurus** [comment]
Nice! Thank you so much, I didn't think of adding it to npm, glad someone did.

**Comment by shukriadams** [comment]
Glad to help out. Your project seems pretty stable, but if at some point you start major work on it, please poke me. Either I'll sync the changes, or hand control of the npm package to you - whatever's easier.

**Comment by surrsurus** [comment]
Will do, I've been considering support for other languages, but not sure when work will start.
